
title: Rizal Zainal
description: Rizal Zainal's portfolio
url: "http://rizalzainal.com"
github_username:  doczal
repository: doczal/doczal.github.io

# Build settings
markdown: kramdown
#theme: minima
gems:
  - jekyll-seo-tag


exclude: ["Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json"]


sass:
  sass_dir: assets/css
